 
services:
  dns:
    build: 
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"

  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"
    depends_on:
      - asa-server
    networks:
      - asa-network

  asa-server:
    build: 
      context: ./asa-server
      dockerfile: Dockerfile
    container_name: asa-server
    networks:
      - asa-network

  asa-server2:
    build: 
      context: ./asa-server02
      dockerfile: Dockerfile
    container_name: asa-server02
    networks:
      - asa-network

  email:
    build: 
      context: ./email
      dockerfile: Dockerfile
    container_name: email
    ports:
      - "25:25/tcp"   # SEMP
      - "587:587/tcp" # SMP Client
      - "110:110/tcp" # POP3
      - "143:143/tcp" # IMAP
    networks:
      - asa-network

#Docker Networks
networks:
  asa-network:
    driver: bridge